# -*- ispell-local-dictionary: "american" -*-
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Making one's work reproducible: Tutorial
#+AUTHOR: Christophe Pouzat
#+EMAIL: christophe.pouzat@parisdescartes.fr
#+DATE: LASCON, January 19 2018, Tutorial 1
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.1 (Org mode 9.0.9)
#+LaTeX_CLASS: koma-article
#+LaTeX_CLASS_OPTIONS: [koma,11pt]
#+LaTeX_HEADER: \usepackage{cmbright}
#+LaTeX_HEADER: \usepackage[round]{natbib}
#+LaTeX_HEADER: \usepackage{alltt}
#+LaTeX_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER: \renewenvironment{verbatim}{\begin{alltt} \scriptsize \color{Bittersweet} \vspace{0.2cm} }{\vspace{0.2cm} \end{alltt} \normalsize \color{black}}
#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \lstloadlanguages{C,Gnuplot,bash,sh,R}
#+LaTeX_HEADER: \hypersetup{colorlinks=true,pagebackref=true}
#+STARTUP: indent
#+PROPERTY: header-args :eval no-export

* Setup :noexport:
#+NAME: org-latex-set-up
#+BEGIN_SRC emacs-lisp :results silent :exports none 
(setq smartparens-mode nil)
(require 'ox-latex)
(setq org-export-latex-listings t)
(setq org-latex-listings 'listings)
(setq org-latex-listings-options
        '(("frame" "lines")
          ("basicstyle" "\\footnotesize")
          ("numbers" "left")
          ("numberstyle" "\\tiny")))
(add-to-list 'org-latex-classes
          '("koma-article"
             "\\documentclass{scrartcl}"
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
(setq org-latex-pdf-process
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	"bibtex %b" 
	"pdflatex -interaction nonstopmode -output-directory %o %f" 
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
#+END_SRC

#+NAME: set-gnuplot-pars
#+BEGIN_SRC gnuplot :session *gnuplot* :results silent :eval no-export :exports none 
set terminal pngcairo size 1000,1000
#+END_SRC

#+NAME: stderr-redirection
#+BEGIN_SRC emacs-lisp :exports none
;; Redirect stderr output to stdout so that it gets printed correctly (found on
;; http://kitchingroup.cheme.cmu.edu/blog/2015/01/04/Redirecting-stderr-in-org-mode-shell-blocks/
(setq org-babel-default-header-args:sh
      '((:prologue . "exec 2>&1") (:epilogue . ":"))
      )
(setq org-babel-use-quick-and-dirty-noweb-expansion t)
#+END_SRC

#+RESULTS: stderr-redirection
: t

* Collective work                                                    :export:

How do you guys take notes? When you listen to a talk / lecture, when you read a paper, when you read a book.

Does anyone use PDF annotation on a regular basis?

* Excercise with Markdown :export:
What follows is an adaptation of [[https://guides.github.com/features/mastering-markdown/][Mastering Markdown]].

** Let's start our first Markdown file!
Open a text file, that you can call =my_first_markdown.md= or anything else you like, with your favorite text editor and type:

#+BEGIN_EXAMPLE
It's very easy to make some words **bold** and other words *italic* with Markdown. 
You can even [link to Lascon's program!](http://sisne.org/lascon-vii/program/?lang=en)
#+END_EXAMPLE

Save the file, upload it (commit it) to you GitHub repository and visualize it with GitHub.

Keep going by opening the file and...

** Headers

#+BEGIN_EXAMPLE
# This is a section heading
## This is a sub-section heading
###### This is a 6th order section heading
#+END_EXAMPLE 

** Emphasis

#+BEGIN_EXAMPLE
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_
#+END_EXAMPLE

** Lists

*** Unordered 

#+BEGIN_EXAMPLE
- Item 1
- Item 2
  - Item 2a
  - Item 2b
#+END_EXAMPLE

*** Ordered

#+BEGIN_EXAMPLE
1. Item 1
1. Item 2
1. Item 3
   1. Item 3a
   1. Item 3b
#+END_EXAMPLE

** Images

Start by downloading the Markdown logo from Wikipedia with, for instance:

#+BEGIN_SRC bash :eval never
wget https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg
#+END_SRC

Then add in you file a command inserting the image with a caption:

#+BEGIN_EXAMPLE
![Markdown Logo](Markdown-mark.svg)
#+END_EXAMPLE

** Links

To insert a link, add:

#+BEGIN_EXAMPLE
https://daringfireball.net/projects/markdown/ - automatic!
[Official Markdown website](https://daringfireball.net/projects/markdown/)
#+END_EXAMPLE

** Blockquotes

If you want to site a famous statement of [[http://cristal.inria.fr/~weis/info/commandline.html][In the Beginning was the Command Line]] by Neal Stepheson (a must read):

#+BEGIN_EXAMPLE
> emacs outshines all other editing software in approximately the same 
> way that the noonday sun does the stars. It is not just bigger and 
> brighter; it simply makes everything else vanish.
#+END_EXAMPLE

** Inline code

#+BEGIN_EXAMPLE
In [Python 3](https://docs.python.org/3/tutorial/index.html) tutorial
the first Python expression is `the_world_is_flat = True`.  
#+END_EXAMPLE

** Some Markdown flavors (like the GitHub one) provide many additional features

*** Syntax highlighting

#+BEGIN_EXAMPLE
Section [5.1.3 of Python's tutorial](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)
introduces the _list comprehension_ with:

```python
squares = [x**2 for x in range(10)]
``` 
#+END_EXAMPLE

*** Tables

You can create tables by assembling a list of words and dividing them with hyphens =-= (for the first row), and then separating each column with a pipe =|=:

#+BEGIN_EXAMPLE
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
#+END_EXAMPLE
